incorporate SASL authentication

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -844,6 +844,7 @@ Optional Features:
   --disable-rewrite-domain
                           support for rewriting the sending domain
   --enable-ssl           support for secure connection to mail server
+  --enable-sasl          support for SASL authentication
   --enable-inet6         support for IPv6 transport
   --enable-md5auth         support for MD5 authentication
   --enable-debug          enable debug output
@@ -4083,6 +4084,88 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_crypto_X509_free" >&5
 echo "${ECHO_T}$ac_cv_lib_crypto_X509_free" >&6
 if test $ac_cv_lib_crypto_X509_free = yes; then
   LIBS="$LIBS -lcrypto"
+fi
+
+fi
+enableval=""
+
+# Check whether --enable-sasl or --disable-sasl was given.
+if test "${enable_sasl+set}" = set; then
+  enableval="$enable_sasl"
+
+fi;
+if test x$enableval = xyes ; then
+	echo "$as_me:$LINENO: checking for sasl_decode64 in -lsasl2" >&5
+echo $ECHO_N "checking for sasl_decode64 in -lsasl2... $ECHO_C" >&6
+if test "${ac_cv_lib_sasl2_sasl_decode64+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsasl2  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char sasl_decode64 ();
+int
+main ()
+{
+sasl_decode64 ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_sasl2_sasl_decode64=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_sasl2_sasl_decode64=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_sasl2_sasl_decode64" >&5
+echo "${ECHO_T}$ac_cv_lib_sasl2_sasl_decode64" >&6
+if test $ac_cv_lib_sasl2_sasl_decode64 = yes; then
+
+			cat >>confdefs.h <<\_ACEOF
+#define HAVE_SASL 1
+_ACEOF
+
+			LIBS="$LIBS -lsasl2"
 fi
 
 fi
